global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'gmail-notifications'

receivers:
- name: 'gmail-notifications'
  email_configs:
  - to: azmo96@gmail.com
    from: azmo96@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: azmo96@gmail.com
    auth_identity: azmo96@gmail.com
    auth_password: kogpwuicbmnxknwa
    send_resolved: true

route:
  group_by: [Alertname]
  receiver: 'team-1'

receivers:
- name: 'team-1'
  slack_configs:
  - 
    channel: '#alert'