route:
  group_by: [Alertname]
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: ahmed.mohamed_97@yahoo.com
    from: azmo96@yahoo.com
    smarthost: smtp.gmail.com:587
    auth_username: azmo96
    auth_password: kogpwuicbmnxknwa