global:
  scrape_interval: 15s
  external_labels:
    monitor: 'prometheus'

rule_files:
 - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
  - static_configs:
    - targets: # state the target public dns u want to set an alert on
      - localhost:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs: # Insert the public dns for the node-exporter instance
      - targets: ['ec2-44-202-122-135.compute-1.amazonaws.com:9100']
  
#  - job_name: 'node'
#    ec2_sd_configs:
#      - region: us-east-1
#        access_key: PUT_THE_ACCESS_KEY_HERE
#        secret_key: PUT_THE_SECRET_KEY_HERE
#        port: 9100